#!/bin/bash

# Detect which `ls` flavor is in use
if ls --color > /dev/null 2>&1; then # GNU `ls`
    colorflag="--color"
else # OS X `ls`
    colorflag="-G"
fi

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Easier navigation
alias ~="cd ~"                                                      # ~:            Go Home
alias cd..='cd ../'                                                 # Go back 1 directory level (for fast typers)
alias ..='cd ../'                                                   # Go back 1 directory level
alias ...='cd ../../'                                               # Go back 2 directory levels
alias .3='cd ../../../'                                             # Go back 3 directory levels
alias .4='cd ../../../../'                                          # Go back 4 directory levels
alias .5='cd ../../../../../'                                       # Go back 5 directory levels
alias .6='cd ../../../../../../'                                    # Go back 6 directory levels
alias -- -="cd -"

# Shortcuts
alias h="history"

# List files
alias ll='ls -FGlAhp'                                               # Preferred 'ls' implementation
alias l="ls -lF ${colorflag}"                                       # List all files colorized in long format
alias la="ls -laF ${colorflag}"                                     # List all files colorized in long format, including dot files
alias lsd="ls -lF ${colorflag} | grep --color=never '^d'"           # List only directories
alias ls="command ls ${colorflag}"                                  # Always use color output for `ls
alias lr='ls -R | grep ":$" | sed -e '\''s/:$//'\'' -e '\''s/[^-][^\/]*\//--/g'\'' -e '\''s/^/   /'\'' -e '\''s/-/|/'\'' | less'

alias cp='cp -iv'                                                   # Preferred 'cp' implementation
alias mv='mv -iv'                                                   # Preferred 'mv' implementation
alias mkdir='mkdir -pv'                                             # Preferred 'mkdir' implementation

#alias edit='subl'                                                   # edit:         Opens any file in sublime editor
alias f='open -a Finder ./'                                         # f:            Opens current directory in MacOS Finder
alias which='type -all'                                             # which:        Find executables
alias path='echo -e ${PATH//:/\\n}'                                 # path:         Echo all executable Paths
alias show_options='shopt'                                          # Show_options: display bash options settings
alias fix_stty='stty sane'                                          # fix_stty:     Restore terminal settings when screwed up
alias cic='set completion-ignore-case On'                           # cic:          Make tab-completion case-insensitive
alias battery='ioreg -w0 -l | grep Capacity | cut -d " " -f 17-50'  # display battery info
alias DT='tee ~/Desktop/terminalOut.txt'                            # DT:           Pipe content to file on MacOS Desktop
alias less='less -FSRXc'                                            # Preferred 'less' implementation
alias updatedb="sudo /usr/libexec/locate.updatedb"

# Always enable colored `grep` output
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

#   memHogsTop, memHogsPs:  Find memory hogs
#   -----------------------------------------------------
alias memHogsTop='top -l 1 -o rsize | head -20'
alias memHogsPs='ps wwaxm -o pid,stat,vsize,rss,time,command | head -10'

#   cpuHogs:  Find CPU hogs
#   -----------------------------------------------------
alias cpuHogsPs='ps wwaxr -o pid,stat,%cpu,time,command | head -10'

#   topForever:  Continual 'top' listing (every 10 seconds)
#   -----------------------------------------------------
alias topForever='top -l 9999999 -s 10 -o cpu'

#   ttop:  Recommended 'top' invocation to minimize resources
#   ------------------------------------------------------------
#       Taken from this macosxhints article
#       http://www.macosxhints.com/article.php?story=20060816123853639
#   ------------------------------------------------------------
alias ttop="top -R -F -s 10 -o rsize"

alias numFiles='echo $(ls -1 | wc -l)'                              # numFiles:     Count of non-hidden files in current dir

alias make1mb='mkfile 1m ./1MB.dat'                                 # make1mb:      Creates a file of 1mb size (all zeros)
alias make5mb='mkfile 5m ./5MB.dat'                                 # make5mb:      Creates a file of 5mb size (all zeros)
alias make10mb='mkfile 10m ./10MB.dat'                              # make10mb:     Creates a file of 10mb size (all zeros)

# `cat` with beautiful colors
alias cc='pygmentize -O style=monokai -f console256 -g'

# Get OS X Software Updates, and update installed Ruby gems, Homebrew, npm, and their installed packages
alias update='sudo softwareupdate -i -a; brew update; brew upgrade --all; brew cleanup; npm install npm -g; npm update -g; sudo gem update --system; sudo gem update'

# Flush Directory Service cache
alias clear-dns-cache='dscacheutil -flushcache && killall -HUP mDNSResponder'

# Clean up LaunchServices to remove duplicates in the “Open With” menu
alias lscleanup="/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user && killall Finder"

# View HTTP traffic
alias sniff="sudo ngrep -d 'en1' -t '^(GET|POST) ' 'tcp and port 80'"
alias httpdump="sudo tcpdump -i en1 -n -s 0 -w - | grep -a -o -E \"Host\: .*|GET \/.*\""

# Trim new lines and copy to clipboard
alias cn="tr -d '\n' | pbcopy"

# Hide/Show hidden files in Finder
alias hide-hidden-files='defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder'
alias show-hidden-files='defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder'

# Hide/show all desktop icons (useful when presenting)
alias hidedesktop="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
alias showdesktop="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"

# Disable/Enable Spotlight
alias spotoff="sudo mdutil -a -i off"
alias spoton="sudo mdutil -a -i on"

# PlistBuddy alias, because sometimes `defaults` just doesn’t cut it
alias plistbuddy="/usr/libexec/PlistBuddy"

# Ring the terminal bell, and put a badge on Terminal.app’s Dock icon (useful when executing time-consuming commands)
alias badge="tput bel"

# Intuitive map function
# For example, to list all directories that contain a certain file:
# find . -name .gitattributes | map dirname
alias map="xargs -n1"

# Lock the screen (when going AFK)
alias afk="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"

# Reload the shell (i.e. invoke as a login shell)
alias reload="exec $SHELL -l"

#export LS_COLORS='no=00:fi=00:di=01;34:ln=01;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.gz=01;31:*.bz2=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.avi=01;35:*.fli=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.ogg=01;35:*.mp3=01;35:*.wav=01;35:'
