#!/bin/bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Clear DNS cache
alias clear-dns-cache='sudo dscacheutil -flushcache; \
                       sudo killall -HUP mDNSResponder'

# Hide/Show hidden files in Finder
alias hide-hidden-files='defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder'
alias show-hidden-files='defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder'

alias ~="cd ~"                                                      # ~:            Go Home
alias cd..='cd ../'                                                 # Go back 1 directory level (for fast typers)
alias ..='cd ../'                                                   # Go back 1 directory level
alias ...='cd ../../'                                               # Go back 2 directory levels
alias .3='cd ../../../'                                             # Go back 3 directory levels
alias .4='cd ../../../../'                                          # Go back 4 directory levels
alias .5='cd ../../../../../'                                       # Go back 5 directory levels
alias .6='cd ../../../../../../'                                    # Go back 6 directory levels
alias updatedb="sudo /usr/libexec/locate.updatedb"
alias cp='cp -iv'                                                   # Preferred 'cp' implementation
alias mv='mv -iv'                                                   # Preferred 'mv' implementation
alias mkdir='mkdir -pv'                                             # Preferred 'mkdir' implementation
alias ll='ls -FGlAhp'                                               # Preferred 'ls' implementation
alias ls='ls -FG'
alias lsd='ll | grep "^d"'                                          # Preferred 'ls' implementation (only directories)
#alias edit='subl'                                                   # edit:         Opens any file in sublime editor
alias f='open -a Finder ./'                                         # f:            Opens current directory in MacOS Finder
alias which='type -all'                                             # which:        Find executables
alias path='echo -e ${PATH//:/\\n}'                                 # path:         Echo all executable Paths
alias show_options='shopt'                                          # Show_options: display bash options settings
alias fix_stty='stty sane'                                          # fix_stty:     Restore terminal settings when screwed up
alias cic='set completion-ignore-case On'                           # cic:          Make tab-completion case-insensitive
alias battery='ioreg -w0 -l | grep Capacity | cut -d " " -f 17-50'  # display battery info
alias DT='tee ~/Desktop/terminalOut.txt'                            # DT:           Pipe content to file on MacOS Desktop
alias grep='grep --color=auto'
alias less='less -FSRXc'                                            # Preferred 'less' implementation
