#!/bin/bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

cd() { builtin cd "$@"; ll; }                                       # Always list directory contents upon 'cd'
mcd () { mkdir -p "$1" && cd "$1"; }                                # mcd:          Makes new Dir and jumps inside
trash () { command mv "$@" ~/.Trash ; }                             # trash:        Moves a file to the MacOS trash
ql () { qlmanage -p "$*" >& /dev/null; }                            # ql:           Opens any file in MacOS Quicklook Preview
